- hosts: rp
  become: true
  pre_tasks:
  - set_fact:
      backends: "{{ (backends | default([])) | union( [{'name':item,'address': hostvars[item]['ansible_host']+':80'}] ) }}"
    with_items: "{{ groups['webservers'] }}"
  roles:
    - role: geerlingguy.haproxy
      become: true
      vars:
        haproxy_backend_servers: "{{ backends }}"
        proxy_backend_balance_method: 'roundrobin'  
      
